// Code generated by protoc-gen-go. DO NOT EDIT.
// Simplified version for compilation

package proto

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// C2S_LoginRequest 登录请求
type C2S_LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *C2S_LoginRequest) Reset()         { *x = C2S_LoginRequest{} }
func (x *C2S_LoginRequest) String() string { return "C2S_LoginRequest{}" }
func (*C2S_LoginRequest) ProtoMessage()    {}
func (x *C2S_LoginRequest) GetUsername() string {
	if x != nil { return x.Username }
	return ""
}
func (x *C2S_LoginRequest) GetPassword() string {
	if x != nil { return x.Password }
	return ""
}

// C2S_RegisterRequest 注册请求
type C2S_RegisterRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *C2S_RegisterRequest) Reset()         { *x = C2S_RegisterRequest{} }
func (x *C2S_RegisterRequest) String() string { return "C2S_RegisterRequest{}" }
func (*C2S_RegisterRequest) ProtoMessage()    {}
func (x *C2S_RegisterRequest) GetUsername() string {
	if x != nil { return x.Username }
	return ""
}
func (x *C2S_RegisterRequest) GetPassword() string {
	if x != nil { return x.Password }
	return ""
}
func (x *C2S_RegisterRequest) GetEmail() string {
	if x != nil { return x.Email }
	return ""
}

// C2S_MoveRequest 移动请求
type C2S_MoveRequest struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *C2S_MoveRequest) Reset()         { *x = C2S_MoveRequest{} }
func (x *C2S_MoveRequest) String() string { return "C2S_MoveRequest{}" }
func (*C2S_MoveRequest) ProtoMessage()    {}
func (x *C2S_MoveRequest) GetX() int32 {
	if x != nil { return x.X }
	return 0
}
func (x *C2S_MoveRequest) GetY() int32 {
	if x != nil { return x.Y }
	return 0
}

// C2S_BuildRequest 建造请求
type C2S_BuildRequest struct {
	BuildingType string `protobuf:"bytes,1,opt,name=building_type,proto3" json:"building_type,omitempty"`
	X            int32  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y            int32  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *C2S_BuildRequest) Reset()         { *x = C2S_BuildRequest{} }
func (x *C2S_BuildRequest) String() string { return "C2S_BuildRequest{}" }
func (*C2S_BuildRequest) ProtoMessage()    {}
func (x *C2S_BuildRequest) GetBuildingType() string {
	if x != nil { return x.BuildingType }
	return ""
}
func (x *C2S_BuildRequest) GetX() int32 {
	if x != nil { return x.X }
	return 0
}
func (x *C2S_BuildRequest) GetY() int32 {
	if x != nil { return x.Y }
	return 0
}

// S2C_LoginResponse 登录响应
type S2C_LoginResponse struct {
	Success    bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message    string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayerId   uint64      `protobuf:"varint,3,opt,name=player_id,proto3" json:"player_id,omitempty"`
	PlayerData *PlayerData `protobuf:"bytes,4,opt,name=player_data,proto3" json:"player_data,omitempty"`
}

func (x *S2C_LoginResponse) Reset()         { *x = S2C_LoginResponse{} }
func (x *S2C_LoginResponse) String() string { return "S2C_LoginResponse{}" }
func (*S2C_LoginResponse) ProtoMessage()    {}
func (x *S2C_LoginResponse) GetSuccess() bool {
	if x != nil { return x.Success }
	return false
}
func (x *S2C_LoginResponse) GetMessage() string {
	if x != nil { return x.Message }
	return ""
}
func (x *S2C_LoginResponse) GetPlayerId() uint64 {
	if x != nil { return x.PlayerId }
	return 0
}
func (x *S2C_LoginResponse) GetPlayerData() *PlayerData {
	if x != nil { return x.PlayerData }
	return nil
}

// S2C_RegisterResponse 注册响应
type S2C_RegisterResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PlayerId uint64 `protobuf:"varint,3,opt,name=player_id,proto3" json:"player_id,omitempty"`
}

func (x *S2C_RegisterResponse) Reset()         { *x = S2C_RegisterResponse{} }
func (x *S2C_RegisterResponse) String() string { return "S2C_RegisterResponse{}" }
func (*S2C_RegisterResponse) ProtoMessage()    {}
func (x *S2C_RegisterResponse) GetSuccess() bool {
	if x != nil { return x.Success }
	return false
}
func (x *S2C_RegisterResponse) GetMessage() string {
	if x != nil { return x.Message }
	return ""
}
func (x *S2C_RegisterResponse) GetPlayerId() uint64 {
	if x != nil { return x.PlayerId }
	return 0
}

// S2C_MoveResponse 移动响应
type S2C_MoveResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	X       int32  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *S2C_MoveResponse) Reset()         { *x = S2C_MoveResponse{} }
func (x *S2C_MoveResponse) String() string { return "S2C_MoveResponse{}" }
func (*S2C_MoveResponse) ProtoMessage()    {}
func (x *S2C_MoveResponse) GetSuccess() bool {
	if x != nil { return x.Success }
	return false
}
func (x *S2C_MoveResponse) GetMessage() string {
	if x != nil { return x.Message }
	return ""
}
func (x *S2C_MoveResponse) GetX() int32 {
	if x != nil { return x.X }
	return 0
}
func (x *S2C_MoveResponse) GetY() int32 {
	if x != nil { return x.Y }
	return 0
}

// S2C_BuildResponse 建造响应
type S2C_BuildResponse struct {
	Success  bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Building *Building `protobuf:"bytes,3,opt,name=building,proto3" json:"building,omitempty"`
}

func (x *S2C_BuildResponse) Reset()         { *x = S2C_BuildResponse{} }
func (x *S2C_BuildResponse) String() string { return "S2C_BuildResponse{}" }
func (*S2C_BuildResponse) ProtoMessage()    {}
func (x *S2C_BuildResponse) GetSuccess() bool {
	if x != nil { return x.Success }
	return false
}
func (x *S2C_BuildResponse) GetMessage() string {
	if x != nil { return x.Message }
	return ""
}
func (x *S2C_BuildResponse) GetBuilding() *Building {
	if x != nil { return x.Building }
	return nil
}

// PlayerData 玩家数据
type PlayerData struct {
	PlayerId   uint64            `protobuf:"varint,1,opt,name=player_id,proto3" json:"player_id,omitempty"`
	Username   string            `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email      string            `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Level      int32             `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Experience int64             `protobuf:"varint,5,opt,name=experience,proto3" json:"experience,omitempty"`
	X          int32             `protobuf:"varint,6,opt,name=x,proto3" json:"x,omitempty"`
	Y          int32             `protobuf:"varint,7,opt,name=y,proto3" json:"y,omitempty"`
	Resources  map[string]int64  `protobuf:"bytes,8,rep,name=resources,proto3" json:"resources,omitempty"`
	Buildings  []*Building       `protobuf:"bytes,9,rep,name=buildings,proto3" json:"buildings,omitempty"`
	CreatedAt  int64             `protobuf:"varint,15,opt,name=created_at,proto3" json:"created_at,omitempty"`
	LastLogin  int64             `protobuf:"varint,16,opt,name=last_login,proto3" json:"last_login,omitempty"`
}

func (x *PlayerData) Reset()         { *x = PlayerData{} }
func (x *PlayerData) String() string { return "PlayerData{}" }
func (*PlayerData) ProtoMessage()    {}
func (x *PlayerData) GetPlayerId() uint64 {
	if x != nil { return x.PlayerId }
	return 0
}
func (x *PlayerData) GetUsername() string {
	if x != nil { return x.Username }
	return ""
}
func (x *PlayerData) GetEmail() string {
	if x != nil { return x.Email }
	return ""
}
func (x *PlayerData) GetLevel() int32 {
	if x != nil { return x.Level }
	return 0
}
func (x *PlayerData) GetExperience() int64 {
	if x != nil { return x.Experience }
	return 0
}
func (x *PlayerData) GetX() int32 {
	if x != nil { return x.X }
	return 0
}
func (x *PlayerData) GetY() int32 {
	if x != nil { return x.Y }
	return 0
}
func (x *PlayerData) GetResources() map[string]int64 {
	if x != nil { return x.Resources }
	return nil
}
func (x *PlayerData) GetBuildings() []*Building {
	if x != nil { return x.Buildings }
	return nil
}
func (x *PlayerData) GetCreatedAt() int64 {
	if x != nil { return x.CreatedAt }
	return 0
}
func (x *PlayerData) GetLastLogin() int64 {
	if x != nil { return x.LastLogin }
	return 0
}

// Building 建筑
type Building struct {
	BuildingId   uint64 `protobuf:"varint,1,opt,name=building_id,proto3" json:"building_id,omitempty"`
	BuildingType string `protobuf:"bytes,2,opt,name=building_type,proto3" json:"building_type,omitempty"`
	Level        int32  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	X            int32  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y            int32  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Building) Reset()         { *x = Building{} }
func (x *Building) String() string { return "Building{}" }
func (*Building) ProtoMessage()    {}
func (x *Building) GetBuildingId() uint64 {
	if x != nil { return x.BuildingId }
	return 0
}
func (x *Building) GetBuildingType() string {
	if x != nil { return x.BuildingType }
	return ""
}
func (x *Building) GetLevel() int32 {
	if x != nil { return x.Level }
	return 0
}
func (x *Building) GetX() int32 {
	if x != nil { return x.X }
	return 0
}
func (x *Building) GetY() int32 {
	if x != nil { return x.Y }
	return 0
}
